-- Удаляем исторические таблицы
DROP TABLE IF EXISTS dwh.DWH_DIM_CARDS_HIST CASCADE;
DROP TABLE IF EXISTS dwh.DWH_DIM_ACCOUNTS_HIST CASCADE;
DROP TABLE IF EXISTS dwh.DWH_DIM_CLIENTS_HIST CASCADE;
DROP TABLE IF EXISTS dwh.DWH_DIM_TERMINALS_HIST CASCADE;
DROP TABLE IF EXISTS dwh.DWH_FACT_TRANSACTIONS CASCADE;
DROP TABLE IF EXISTS dwh.DWH_FACT_PASSPORT_BLACKLIST CASCADE;
DROP TABLE IF EXISTS dwh.REP_FRAUD CASCADE;
DROP TABLE IF EXISTS dwh.META_LOAD_HISTORY CASCADE;
DROP TABLE IF EXISTS dwh.STG_TRANSACTIONS CASCADE;
DROP TABLE IF EXISTS dwh.STG_TERMINALS CASCADE;
DROP TABLE IF EXISTS dwh.STG_PASSPORT_BLACKLIST CASCADE;
